/**
 * bash shell init snippet for `eval "$(maw shellenv bash)"`.
 *
 * Structurally identical to the zsh emitter — both use `[[`, `local`,
 * `${1:-default}`, and `command` (all macOS bash 3.2 friendly). Kept
 * as a separate file so the bash variant can diverge (e.g. completion
 * dialect) without churning the zsh path.
 *
 * See snippets/zsh.ts for the contract.
 */
export function bashSnippet(): string {
  return `# maw shellenv (bash) — generated by 'maw shellenv bash'
# Install: eval "$(maw shellenv bash)"
maw() {
  if [[ "$1" == "warp" ]]; then
    shift
    local target="\${1:-mawjs}"
    if [[ "$target" == *:* ]]; then
      echo "maw warp: qualified <oracle>:<node> not supported yet (see #804)" >&2
      return 1
    fi
    local path
    if ! path="$(command maw locate "$target" --path 2>/dev/null)" || [[ -z "$path" ]]; then
      echo "maw warp: oracle '$target' not found" >&2
      return 1
    fi
    builtin cd "$path"
  else
    command maw "$@"
  fi
}
# TODO(shellenv): tab completion for 'maw warp' via complete -F + 'command maw completions oracles'
`;
}
