/**
 * zsh shell init snippet for `eval "$(maw shellenv zsh)"`.
 *
 * Installs a `maw()` shell function that intercepts `maw warp [<oracle>]`
 * (does an in-shell `cd` via `command maw locate --path`) and passes
 * everything else through to the real binary.
 *
 * IMPORTANT: the function MUST call `command maw …` for the locate
 * fan-out so it does not recurse into itself.
 *
 * Qualified `<oracle>:<node>` targets are refused — federation peer
 * resolution lands with #804 / RFC 629. See issue #812.
 */
export function zshSnippet(): string {
  return `# maw shellenv (zsh) — generated by 'maw shellenv zsh'
# Install: eval "$(maw shellenv zsh)"
maw() {
  if [[ "$1" == "warp" ]]; then
    shift
    local target="\${1:-mawjs}"
    if [[ "$target" == *:* ]]; then
      echo "maw warp: qualified <oracle>:<node> not supported yet (see #804)" >&2
      return 1
    fi
    local path
    if ! path="$(command maw locate "$target" --path 2>/dev/null)" || [[ -z "$path" ]]; then
      echo "maw warp: oracle '$target' not found" >&2
      return 1
    fi
    builtin cd "$path"
  else
    command maw "$@"
  fi
}
# TODO(shellenv): tab completion for 'maw warp' via compdef + 'command maw completions oracles'
`;
}
